### ISSUE TITLE
Update Story and Epic Models

### ISSUE THREAD

**Issue by NiamhGillespie** [NiamhGillespie/Final-year-project#12]
**As a** developer
**I want to** update my Epic and Story models
**So that I** can access new fields in my epic and story detail components

**Definition of done:**

- [x] Epic model has values field
- [x] Story model has tags field
- [x] Story model has state field
- [x] Story model has story points field
- [x] Tests are updated and CI is passing
