### ISSUE TITLE
Let a team add a column to their tracking dashboard

### ISSUE THREAD

**Issue by NiamhGillespie** [NiamhGillespie/Final-year-project#15]
**As an** Agile team
**I want to** be able to add different column to the tracking dashboard
**So that I** can organise stories

**Definition of done:**
- [x] Can add a column
- [x] Can edit a column
- [x] Can delete a column
