### ISSUE TITLE
Add\remove stories to tracking colum

### ISSUE THREAD

**Issue by NiamhGillespie** [NiamhGillespie/Final-year-project#16]
**As an**  Agile team member
**I want to** add stories to one of my team's tracking columns
**So that I** can add stories to the backlog based on the sprint

**Definition of done:**

- [x] User can add stories to a column
- [x] User can remove stories from a column
- [x] Relevant stories are displayed in a tracking column
